@_default:
    just --list

# Runs `check`, `lint`, `format`, `test` in that order
all: check lint format test

# Runs `ty` checks
check *ARGS:
    uv run ty check src tests {{ARGS}}

# Runs `ruff` checks
lint *ARGS:
    uv run ruff check src tests {{ARGS}}

# Runs `ruff` formatting
format *ARGS:
    uv run ruff format src tests {{ARGS}}

# Runs `pytest` on all tests in `tests/`
test *ARGS:
    uv run pytest tests {{ARGS}}
