[project]
name = "e-axle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Mick Harrigan", email = "michael.harrigan@fslabs.ca" }]
requires-python = ">=3.13"
dependencies = [
  "gs-usb>=0.3.1",
  "instro-unstable>=1.11.0",
  "instro[unstable]>=1.20.0",
  "python-can>=4.6.1",
  "pyusb>=1.3.1",
  "pyyaml>=6.0.3",
]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
gs-usb = { git = "https://github.com/MickHarrigan/gs_usb", branch = "mh/fix/optional-start-reset" }

[dependency-groups]
dev = [
  { include-group = "test" },
  { include-group = "lint" },
  { include-group = "check" },
]
test = ["pytest>=9.1.1"]
lint = ["ruff>=0.16.8"]
check = ["ty>=0.0.81"]
reference = ["rich>=15.0.0"]
