name: Run Pytest

on: [push, pull_request]

jobs:
  python-unit-test:
    runs-on: ubuntu-latest
    
    # Define the matrix of Python versions to test against
    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.14']

    steps:
    - name: Checkout code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

    # Dynamically inject the version from the matrix above
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9cv5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests with pytest
      run: |
        pytest
